import { PlatformColor } from 'react-native';

import { setSchemeVariables, setVariables } from '../components/theme_style';

setVariables({
  'bg-color': 'white',
  'text-color': '#1a1a1a',
  'secondary-text-color': '#555555',
  'text-size': 10,
  'light-underlay': 'rgba(0,0,0,0.1)',
  modal: '#f3f2f7',
  'form-box-bg': PlatformColor('secondarySystemGroupedBackground'),
  'form-box-border': '#c6c5c9',
  'search-bg': '#f1f1f1',
  'search-border': '#eee',
  'button-bg': PlatformColor('link'),
  'button-text-color': 'white',
  'bottom-alert-sep': '#b1b0b4',
  'edit-bg': '#f3f2f7',
  'config-bg': '#f3f2f7',
  'config-group-bg': '#ffffff',
  'config-group-border': '#c6c5c9',
  'config-separator': '#e5e5ea',
  'config-radio-border': '#c7c7cc',
  'button-default-bg': '#007aff',
  'button-default-border': '#007aff',
  'button-default-text': '#ffffff',
  'button-blue-bg': '#0a84ff',
  'button-blue-border': '#0a84ff',
  'button-blue-text': '#ffffff',
  'button-danger-bg': '#ff3b30',
  'button-danger-border': '#ff3b30',
  'button-danger-text': '#ffffff',
  'button-ghost-bg': 'transparent',
  'button-ghost-border': '#007aff',
  'button-ghost-text': '#007aff',
  'button-ghost-inverted-bg': 'transparent',
  'button-ghost-inverted-border': '#ffffff',
  'button-ghost-inverted-text': '#ffffff',
  'button-empty-bg': 'transparent',
  'button-empty-border': 'transparent',
  'button-empty-text': '#007aff',
  'button-inverted-bg': '#ffffff',
  'button-inverted-border': '#ffffff',
  'button-inverted-text': '#007aff',
  'button-disabled-bg': '#e5e5ea',
  'button-disabled-border': '#e5e5ea',
  'button-disabled-text': '#8e8e93',
});

setSchemeVariables('light', {
  'bg-color': 'white',
  'text-color': '#1a1a1a',
  'secondary-text-color': '#555555',
});

setSchemeVariables('dark', {
  'bg-color': '#1c1c1e',
  'text-color': '#f0f0f0',
  'secondary-text-color': '#a1a0a6',
  'light-underlay': 'rgba(255,255,255,0.1)',
  modal: '#1c1c1e',
  'form-box-bg': PlatformColor('secondarySystemGroupedBackground'),
  'form-box-border': '#44434a',
  'search-bg': '#333',
  'search-border': '#888',
  'config-bg': '#1c1c1e',
  'config-group-bg': '#2c2c2e',
  'config-group-border': '#3a3a3c',
  'config-separator': '#3a3a3c',
  'config-radio-border': '#636366',
  'button-bg': '#0a84ff',
  'button-text-color': 'white',
  'bottom-alert-sep': '#606060',
  'edit-bg': 'black',
  'button-default-bg': '#0a84ff',
  'button-default-border': '#0a84ff',
  'button-default-text': '#ffffff',
  'button-blue-bg': '#0a84ff',
  'button-blue-border': '#0a84ff',
  'button-blue-text': '#ffffff',
  'button-danger-bg': '#ff453a',
  'button-danger-border': '#ff453a',
  'button-danger-text': '#ffffff',
  'button-ghost-bg': 'transparent',
  'button-ghost-border': '#0a84ff',
  'button-ghost-text': '#0a84ff',
  'button-ghost-inverted-bg': 'transparent',
  'button-ghost-inverted-border': '#f0f0f0',
  'button-ghost-inverted-text': '#f0f0f0',
  'button-empty-bg': 'transparent',
  'button-empty-border': 'transparent',
  'button-empty-text': '#0a84ff',
  'button-inverted-bg': '#f0f0f0',
  'button-inverted-border': '#f0f0f0',
  'button-inverted-text': '#0a84ff',
  'button-disabled-bg': '#2c2c2e',
  'button-disabled-border': '#2c2c2e',
  'button-disabled-text': '#636366',
});
